######################################################################
# Automatically generated by qmake (3.0) Thu Sep 1 17:48:29 2016
######################################################################

TEMPLATE = app
TARGET = dvo_slam
INCLUDEPATH += . dvo_benchmark/include dvo_core/include \
               dvo_ros/include dvo_slam/include \
               /home/mylxiaoyi/source/ros_catkin.kinetic/install_isolated/include \
               /usr/include/eigen3

# Input
HEADERS += dvo_benchmark/include/dvo_benchmark/file_reader.h \
           dvo_benchmark/include/dvo_benchmark/groundtruth.h \
           dvo_benchmark/include/dvo_benchmark/rgbd_pair.h \
           dvo_benchmark/include/dvo_benchmark/tools.h \
           dvo_core/include/dvo/dense_tracking.h \
           dvo_core/include/dvo/dense_tracking_impl.h \
           dvo_ros/include/dvo_ros/camera_base.h \
           dvo_ros/include/dvo_ros/camera_dense_tracking.h \
           dvo_ros/include/dvo_ros/camera_tracker_nodelet.h \
           dvo_slam/include/dvo_slam/camera_keyframe_tracking.h \
           dvo_slam/include/dvo_slam/config.h \
           dvo_slam/include/dvo_slam/keyframe.h \
           dvo_slam/include/dvo_slam/keyframe_constraint_search.h \
           dvo_slam/include/dvo_slam/keyframe_graph.h \
           dvo_slam/include/dvo_slam/keyframe_tracker.h \
           dvo_slam/include/dvo_slam/local_map.h \
           dvo_slam/include/dvo_slam/local_tracker.h \
           dvo_slam/include/dvo_slam/timestamped.h \
           dvo_slam/include/dvo_slam/tracking_result_evaluation.h \
           dvo_core/include/dvo/core/datatypes.h \
           dvo_core/include/dvo/core/interpolation.h \
           dvo_core/include/dvo/core/intrinsic_matrix.h \
           dvo_core/include/dvo/core/least_squares.h \
           dvo_core/include/dvo/core/math_sse.h \
           dvo_core/include/dvo/core/point_selection.h \
           dvo_core/include/dvo/core/point_selection_predicates.h \
           dvo_core/include/dvo/core/rgbd_image.h \
           dvo_core/include/dvo/core/surface_pyramid.h \
           dvo_core/include/dvo/core/weight_calculation.h \
           dvo_core/include/dvo/util/fluent_interface.h \
           dvo_core/include/dvo/util/histogram.h \
           dvo_core/include/dvo/util/id_generator.h \
           dvo_core/include/dvo/util/revertable.h \
           dvo_core/include/dvo/util/stopwatch.h \
           dvo_core/include/dvo/visualization/async_point_cloud_builder.h \
           dvo_core/include/dvo/visualization/camera_trajectory_visualizer.h \
           dvo_core/include/dvo/visualization/pcl_camera_trajectory_visualizer.h \
           dvo_core/include/dvo/visualization/point_cloud_aggregator.h \
           dvo_ros/cfg/cpp/dvo_ros/CameraDenseTrackerConfig.h \
           dvo_ros/include/dvo_ros/util/configtools.h \
           dvo_ros/include/dvo_ros/util/util.h \
           dvo_ros/include/dvo_ros/visualization/ros_camera_trajectory_visualizer.h \
           dvo_slam/include/dvo_slam/constraints/constraint_proposal.h \
           dvo_slam/include/dvo_slam/constraints/constraint_proposal_validator.h \
           dvo_slam/include/dvo_slam/constraints/constraint_proposal_voter.h \
           dvo_slam/include/dvo_slam/serialization/map_serializer.h \
           dvo_slam/include/dvo_slam/serialization/map_serializer_interface.h \
           dvo_slam/include/dvo_slam/visualization/graph_visualizer.h
SOURCES += dvo_benchmark/src/benchmark.cpp \
           dvo_benchmark/src/benchmark_slam.cpp \
           dvo_benchmark/src/experiment.cpp \
           dvo_core/src/dense_tracking.cpp \
           dvo_core/src/dense_tracking_config.cpp \
           dvo_core/src/dense_tracking_impl.cpp \
           dvo_core/src/sse_test.cpp \
           dvo_ros/src/camera_base.cpp \
           dvo_ros/src/camera_dense_tracking.cpp \
           dvo_ros/src/camera_tracker_node.cpp \
           dvo_ros/src/camera_tracker_nodelet.cpp \
           dvo_slam/src/camera_keyframe_tracker_node.cpp \
           dvo_slam/src/camera_keyframe_tracking.cpp \
           dvo_slam/src/config.cpp \
           dvo_slam/src/keyframe.cpp \
           dvo_slam/src/keyframe_constraint_search.cpp \
           dvo_slam/src/keyframe_graph.cpp \
           dvo_slam/src/keyframe_tracker.cpp \
           dvo_slam/src/local_map.cpp \
           dvo_slam/src/local_tracker.cpp \
           dvo_slam/src/tracking_result_evaluation.cpp \
           dvo_slam/src/types.cpp \
           dvo_core/src/core/interpolation.cpp \
           dvo_core/src/core/intrinsic_matrix.cpp \
           dvo_core/src/core/least_squares.cpp \
           dvo_core/src/core/math_sse.cpp \
           dvo_core/src/core/point_selection.cpp \
           dvo_core/src/core/rgbd_image.cpp \
           dvo_core/src/core/rgbd_image_sse.cpp \
           dvo_core/src/core/surface_pyramid.cpp \
           dvo_core/src/core/weight_calculation.cpp \
           dvo_core/src/util/histogram.cpp \
           dvo_core/src/util/id_generator.cpp \
           dvo_core/src/visualization/async_point_cloud_builder.cpp \
           dvo_core/src/visualization/camera_trajectory_visualizer.cpp \
           dvo_core/src/visualization/pcl_camera_trajetory_visualizer.cpp \
           dvo_core/src/visualization/point_cloud_aggregator.cpp \
           dvo_ros/src/visualization/ros_camera_trajectory_visualizer.cpp \
           dvo_slam/src/constraints/constraint_proposal.cpp \
           dvo_slam/src/constraints/constraint_proposal_validator.cpp \
           dvo_slam/src/constraints/constraint_proposal_voter.cpp \
           dvo_slam/src/serialization/map_serializer.cpp \
           dvo_slam/src/serialization/map_serializer_interface.cpp \
           dvo_slam/src/visualization/graph_visualizer.cpp
